/* Auto-generated by component2block — do not edit manually */

export const octaveTokens = {
    color: {
        black: '#191919',
        white: '#ffffff',
        info: '#2571eb',
        success: '#16a34a',
        warning: '#fff154',
        error: '#dc2626',
        linkedin: '#0A66C2',
        facebook: '#1877F2',
        bluesky: '#1185FE',
        twitter: '#000000',
        instagram: '#E4405F',
        youtube: '#FF0000',
        tiktok: '#010101'
    },
    gradient: {
        whiteToPaleGrey: 'linear-gradient(135deg,rgb(250,250,250) 0%,rgb(245,245,245) 90%)'
    },
    spacing: {
        x3Small: '0.175rem',
        x2Small: '0.25rem',
        xSmall: '0.5rem',
        small: 'clamp(0.625rem, 0.625rem + ((1vw - 0.2rem) * 0.240), 0.75rem)',
        normal: 'clamp(0.8125rem, 0.8125rem + ((1vw - 0.2rem) * 0.361), 1rem)',
        medium: 'clamp(0.9375rem, 0.9375rem + ((1vw - 0.2rem) * 0.601), 1.25rem)',
        large: 'clamp(1.0625rem, 1.0625rem + ((1vw - 0.2rem) * 0.841), 1.5rem)',
        xLarge: 'clamp(1.1875rem, 1.1875rem + ((1vw - 0.2rem) * 1.563), 2rem)',
        x2Large: 'clamp(1.3125rem, 1.3125rem + ((1vw - 0.2rem) * 2.284), 2.5rem)',
        x3Large: 'clamp(1.4375rem, 1.4375rem + ((1vw - 0.2rem) * 3.005), 3rem)',
        x4Large: 'clamp(1.625rem, 1.625rem + ((1vw - 0.2rem) * 4.567), 4rem)',
        x5Large: 'clamp(1.75rem, 1.75rem + ((1vw - 0.2rem) * 6.250), 5rem)'
    },
    fontFamily: {
        interTight: 'Inter Tight, system-ui, Segoe UI, roboto, sans-serif',
        sourceSerif4: 'Source Serif 4, ui-serif, georgia, serif',
        jetbrainsMono: 'JetBrains Mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace'
    },
    fontSize: {
        xSmall: 'clamp(0.7rem, 0.7rem + ((1vw - 0.2rem) * 0.096), 0.75rem)',
        small: 'clamp(0.8rem, 0.8rem + ((1vw - 0.2rem) * 0.192), 0.9rem)',
        medium: 'clamp(0.85rem, 0.85rem + ((1vw - 0.2rem) * 0.288), 1rem)',
        large: 'clamp(0.9rem, 0.9rem + ((1vw - 0.2rem) * 0.433), 1.125rem)',
        xLarge: 'clamp(1.05rem, 1.05rem + ((1vw - 0.2rem) * 0.385), 1.25rem)',
        x2Large: 'clamp(1.25rem, 1.25rem + ((1vw - 0.2rem) * 0.481), 1.5rem)',
        headingSmall: 'clamp(1rem, 1rem + ((1vw - 0.2rem) * 0.962), 1.5rem)',
        headingMedium: 'clamp(1.25rem, 1.25rem + ((1vw - 0.2rem) * 0.962), 1.75rem)',
        headingLarge: 'clamp(1.5rem, 1.5rem + ((1vw - 0.2rem) * 1.442), 2.25rem)',
        headingXLarge: 'clamp(1.75rem, 1.75rem + ((1vw - 0.2rem) * 1.442), 2.5rem)',
        headingPrimary: 'clamp(1.75rem, 1.75rem + ((1vw - 0.2rem) * 2.404), 3rem)'
    },
    shadow: {
        natural: '6px 6px 9px rgba(0, 0, 0, 0.2)',
        deep: '12px 12px 50px rgba(0, 0, 0, 0.4)',
        sharp: '6px 6px 0px rgba(0, 0, 0, 0.2)',
        outlined: '6px 6px 0px -3px rgb(255, 255, 255), 6px 6px rgb(0, 0, 0)',
        crisp: '6px 6px 0px rgb(0, 0, 0)'
    },
    fontWeight: {
        thin: '100',
        extraLight: '200',
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extraBold: '800',
        black: '900'
    },
    lineHeight: {
        tight: '1.3',
        normal: '1.6',
        loose: '1.8'
    },
    radius: {
        sm: '2px',
        md: '4px',
        lg: '8px',
        xl: '12px',
        full: '9999px'
    },
    transition: {
        fast: '150ms ease',
        base: '250ms ease'
    },
    z: {
        '100': '100',
        '200': '200',
        '500': '500'
    },
    layout: {
        contentSize: '768px',
        wideSize: '1152px',
        smallSize: '600px',
        fullSize: '100vw'
    },
    viewport: {
        mobile: '600px',
        tablet: '768px'
    }
};

export default octaveTokens;
