/* Auto-generated by component2block — do not edit manually */

export declare const octaveTokens: Record<string, Record<string, string>>;
export declare const octaveTokenKeys: {
    readonly color: { readonly black: 'black'; readonly white: 'white'; readonly 'accent-primary': 'accent-primary'; readonly 'accent-secondary': 'accent-secondary'; readonly 'neutral-50': 'neutral-50'; readonly 'neutral-100': 'neutral-100'; readonly 'neutral-200': 'neutral-200'; readonly 'neutral-300': 'neutral-300'; readonly 'neutral-400': 'neutral-400'; readonly 'neutral-500': 'neutral-500'; readonly 'neutral-600': 'neutral-600'; readonly 'neutral-700': 'neutral-700'; readonly 'neutral-800': 'neutral-800'; readonly 'neutral-900': 'neutral-900'; readonly 'neutral-950': 'neutral-950'; readonly info: 'info'; readonly success: 'success'; readonly warning: 'warning'; readonly error: 'error'; readonly linkedin: 'linkedin'; readonly facebook: 'facebook'; readonly bluesky: 'bluesky'; readonly twitter: 'twitter'; readonly instagram: 'instagram'; readonly youtube: 'youtube'; readonly tiktok: 'tiktok' };
    readonly gradient: { readonly 'white-to-neutral-50': 'white-to-neutral-50' };
    readonly spacing: { readonly '3-x-small': '3-x-small'; readonly '2-x-small': '2-x-small'; readonly 'x-small': 'x-small'; readonly small: 'small'; readonly normal: 'normal'; readonly medium: 'medium'; readonly large: 'large'; readonly 'x-large': 'x-large'; readonly '2-x-large': '2-x-large'; readonly '3-x-large': '3-x-large'; readonly '4-x-large': '4-x-large'; readonly '5-x-large': '5-x-large' };
    readonly fontFamily: { readonly 'inter-tight': 'inter-tight'; readonly 'source-serif-4': 'source-serif-4'; readonly 'jetbrains-mono': 'jetbrains-mono' };
    readonly fontSize: { readonly '2-x-small': '2-x-small'; readonly 'x-small': 'x-small'; readonly small: 'small'; readonly medium: 'medium'; readonly large: 'large'; readonly 'x-large': 'x-large'; readonly '2-x-large': '2-x-large'; readonly '3-x-large': '3-x-large'; readonly '4-x-large': '4-x-large'; readonly '5-x-large': '5-x-large'; readonly hero: 'hero'; readonly 'heading-small': 'heading-small'; readonly 'heading-medium': 'heading-medium'; readonly 'heading-large': 'heading-large'; readonly 'heading-x-large': 'heading-x-large'; readonly 'heading-primary': 'heading-primary' };
    readonly shadow: { readonly natural: 'natural'; readonly deep: 'deep'; readonly sharp: 'sharp'; readonly outlined: 'outlined'; readonly crisp: 'crisp' };
    readonly fontWeight: { readonly thin: 'thin'; readonly 'extra-light': 'extra-light'; readonly light: 'light'; readonly normal: 'normal'; readonly medium: 'medium'; readonly semibold: 'semibold'; readonly bold: 'bold'; readonly 'extra-bold': 'extra-bold'; readonly black: 'black' };
    readonly lineHeight: { readonly tight: 'tight'; readonly normal: 'normal'; readonly loose: 'loose' };
    readonly radius: { readonly sm: 'sm'; readonly md: 'md'; readonly lg: 'lg'; readonly xl: 'xl'; readonly full: 'full' };
    readonly transition: { readonly fast: 'fast'; readonly base: 'base' };
    readonly z: { readonly '100': '100'; readonly '200': '200'; readonly '500': '500' };
    readonly layout: { readonly 'content-size': 'content-size'; readonly 'wide-size': 'wide-size'; readonly 'small-size': 'small-size'; readonly 'full-size': 'full-size' };
    readonly viewport: { readonly mobile: 'mobile'; readonly tablet: 'tablet' };
};
export default octaveTokens;
