import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { StorybookConfig } from '@storybook/react-vite';
import remarkGfm from 'remark-gfm';

const fontsCssPath = resolve(dirname(fileURLToPath(import.meta.url)), '../public/fonts.css');

const config: StorybookConfig = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
  addons: [{
    name: '@storybook/addon-docs',
    options: {
      mdxPluginOptions: {
        mdxCompileOptions: {
          remarkPlugins: [remarkGfm],
        },
      },
    },
  }, '@storybook/addon-a11y', '@storybook/addon-vitest', '@storybook/addon-mcp'],
  staticDirs: ['../public'],
  // public/fonts.css (generated by c2b) uses root paths, /fonts.css and /fonts/…, which miss when
  // Storybook is served from a subpath such as /parlour-ui/ on GitHub Pages. Inline it with the
  // font URLs made relative to the page instead.
  previewHead: (head) => {
    const fonts = readFileSync(fontsCssPath, 'utf8').replaceAll("url('/fonts/", "url('fonts/");
    return `${head}<style>${fonts}</style>`;
  },
  framework: '@storybook/react-vite',
  typescript: {
    reactDocgen: 'react-docgen-typescript',
  },
  viteFinal: async (config) => {
    // staticDirs already copies public/ into the build. Vite's own publicDir copy writes the same
    // files to the same place at the same time, and the race fails the build with EEXIST.
    config.publicDir = false;

    if (process.env.STORYBOOK_BASE_PATH) {
      config.base = process.env.STORYBOOK_BASE_PATH;
    }
    return config;
  },
};
export default config;
